---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - manage.ksctl.com
  resources:
  - clusteraddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manage.ksctl.com
  resources:
  - clusteraddons/finalizers
  verbs:
  - update
- apiGroups:
  - manage.ksctl.com
  resources:
  - clusteraddons/status
  verbs:
  - get
  - patch
  - update
